// This is the file where all of the rules and terminals are defined
?start: program

program: [_NEWLINE] (global_statement _NEWLINE)* [global_statement]

?global_statement: statement
    | function_defo
    | function_defa

?statement: creation
    | assignment
    | function_call

function_defo: "defo" function_head _NEWLINE [_NEWLINE] ([_WS_INLINE] statement _NEWLINE)* "fino" // _WS_INLINE expression
function_defa: "defa" function_head _NEWLINE [_NEWLINE] ([_WS_INLINE] statement _NEWLINE)* "fina" //_WS_INLINE expression

function_head: _WS_INLINE name "(" ([_WS] parameter [_WS] ",")* [[_WS] parameter] [_WS] ")"

creation: gender _WS_INLINE type _WS_INLINE name _WS_INLINE "=" _WS_INLINE expression

parameter: gender _WS type _WS name

assignment: name _WS_INLINE "=" _WS_INLINE expression

expression: name
    | function_call
    | string
    | num

num: SIGNED_NUMBER gender
string: ESCAPED_STRING gender

function_call: function_conjugation "(" ([_WS] expression [_WS] ",")* [[_WS] expression] [_WS] ")"

?function_conjugation: name

type: "num" -> num_type
    | "bool" -> boolean_type
    | "str" -> string_type

gender: "m" -> m
    | "f" -> f

name: MNAME

MNAME: ("_"|LETTER) ("_"|LETTER|DIGIT)* 

_WS_INLINE: WS_INLINE
_NEWLINE: NEWLINE
_WS: WS

%import common.WS_INLINE
%import common.WS
%import common.CNAME
%import common.NEWLINE
%import common.ESCAPED_STRING
%import common.LETTER
%import common.DIGIT
%import common.SIGNED_NUMBER
%import common.SIGNED_INT